#!/usr/bin/env python3
"""Build courses-data.js for the Chess Mistake Trainer from Chessly raw crawls.

Reads every *-raw.json in this directory (or files passed as arguments) and
emits ../courses-data.js defining window.CMT_COURSES. Loaded via a <script>
tag so the app keeps working from file://.

Each course:
  { id, name, shortName, color: 'w'|'b', chapters: [{id,name}],
    studies: {id: {name, chapterId}},
    positions: { posKey: { moves: [{san, uci}], studies: [studyId] } } }

Position keys use the app's posKey() convention (see core.js): placement,
turn, castling, and the en-passant square ONLY when an ep capture is
pseudo-possible (pawn of the side to move adjacent on the capturing rank).
Chessly FENs use old-style ep (always set after a double push) and carry move
counters; both are normalized away here so keys match game-side keys exactly.

Usage: python3 build_courses_bundle.py [raw.json ...]
"""
import glob
import json
import os
import sys

import chess

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "courses-data.js")


def pos_key(fen):
    """Mirror core.js posKey(): drop counters, keep ep only if pseudo-capturable."""
    placement, turn, castling, ep = fen.split(" ")[:4]
    if ep != "-":
        file = ord(ep[0]) - 97
        rank = 4 if turn == "b" else 5           # rank the capturing pawn stands on
        row = placement.split("/")[8 - rank]
        cells = []
        for ch in row:
            if ch.isdigit():
                cells.extend([None] * int(ch))
            else:
                cells.append(ch)
        pawn = "p" if turn == "b" else "P"
        ok = (file > 0 and cells[file - 1] == pawn) or (file < 7 and cells[file + 1] == pawn)
        if not ok:
            ep = "-"
    return f"{placement} {turn} {castling} {ep}"


def course_color(data):
    meta = data.get("courseMeta") or {}
    c = (meta.get("color") or "").upper()
    if c in ("W", "B"):
        return c.lower()
    tags = " ".join(meta.get("tags") or [])
    if "White" in tags:
        return "w"
    if "Black" in tags:
        return "b"
    raise SystemExit(f"cannot determine course color for {data['course']['name']}; "
                     f"add courseMeta.color ('W'/'B') to the raw json")


def convert(path):
    data = json.load(open(path))
    positions = {}
    dup_conflicts = 0
    for fen, entry in data["positions"].items():
        if not isinstance(entry, dict):
            continue
        board = chess.Board(fen)
        moves = []
        for san in entry.get("m", []):
            mv = board.parse_san(san)
            moves.append({"san": san, "uci": mv.uci()})
        key = pos_key(fen)
        if key in positions:
            # Transpositions with different move counters: merge move lists.
            known = {m["uci"] for m in positions[key]["moves"]}
            for m in moves:
                if m["uci"] not in known:
                    positions[key]["moves"].append(m)
            positions[key]["studies"] = sorted(set(positions[key]["studies"]) | set(entry.get("s", [])))
            dup_conflicts += 1
        else:
            positions[key] = {"moves": moves, "studies": entry.get("s", [])}
    meta = data.get("courseMeta") or {}
    course = {
        "id": data["course"]["id"],
        "name": data["course"]["name"],
        "shortName": meta.get("shortName") or data["course"]["name"],
        "color": course_color(data),
        "url": data["course"].get("url", ""),
        "chapters": data.get("chapters") or [],
        "studies": data.get("studies") or {},
        "positions": positions,
    }
    n_moves = sum(len(p["moves"]) for p in positions.values())
    print(f"  {course['name']}: color={course['color']}, {len(positions)} positions, "
          f"{n_moves} moves, {dup_conflicts} merged transpositions")
    return course


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    files = sys.argv[1:] or sorted(glob.glob(os.path.join(here, "*-raw.json")))
    if not files:
        raise SystemExit("no *-raw.json files found")
    print(f"Building bundle from {len(files)} course file(s):")
    courses = [convert(f) for f in files]
    ids = [c["id"] for c in courses]
    assert len(ids) == len(set(ids)), "duplicate course ids"
    body = json.dumps(courses, separators=(",", ":"))
    with open(OUT, "w") as f:
        f.write("// Generated by chessly-import/build_courses_bundle.py — do not edit.\n")
        f.write("// Regenerate after adding course crawls: python3 chessly-import/build_courses_bundle.py\n")
        f.write("window.CMT_COURSES = ")
        f.write(body)
        f.write(";\n")
    print(f"Wrote {os.path.normpath(OUT)} ({os.path.getsize(OUT) // 1024} KB)")


if __name__ == "__main__":
    main()
